///Project Euler Problem 44
///Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal 
///numbers are:
///
///1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
///
///It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 22 = 48, is not 
///pentagonal.
///
///Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal 
///and D = |Pk - Pj| is minimised; what is the value of D?
//-----------------------------------------------------------------------
// <copyright file="pentagonal.fs" >
//     Copyright © Cesar Mendoza. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
open System
open System.Collections.Generic

let pentagonal n = (n * ((3L * n) - 1L))/2L

let limit = 10000L

let pentagonals, isPentagonal = 
    let hash = new HashSet<int64>()
    [|
        for n in 1L .. limit do
            let p = pentagonal n
            do hash.Add(p) |> ignore
            yield p
    |], (fun n -> hash.Contains(n))

let pairs = 
        seq {
            for j in 0 .. int limit - 2 do
                for k in j+1 .. int limit - 1 do
                    let sum = pentagonals.[k] + pentagonals.[j]
                    let diff = pentagonals.[k] - pentagonals.[j]
                    if (diff |> isPentagonal) && (sum |> isPentagonal)then
                        yield ((pentagonals.[j],pentagonals.[k]),diff)
        }

//pairs |> Seq.length |> printfn "%A"

//pairs |> Seq.iter(printfn "%A")

let solution = pairs |> Seq.minBy snd |> snd

solution |> printfn "solution: %d"

Console.ReadKey(true) |> ignore